### ISSUE TITLE
Get value even if it's not the fully qualified path

### ISSUE THREAD

**Issue by nitrocode** [minamijoyo/hcledit#21]
`test.tf`
```hcl
resource "foo" "bar" {
  attr1 = "val1"
  nested {
    attr2 = "val2"
  }
}
```

Expected this but the last 2 statements returned empty strings

```bash
$ cat test.tf | hcledit attribute get resource.foo.bar.nested.attr2
"val2"
$ cat test.tf | hcledit attribute get resource.foo.bar.attr1
"val1"
$ cat test.tf | hcledit attribute get resource.foo.bar.nested
{
  attr2 = "val2"
}
$ cat test.tf | hcledit attribute get resource.foo.bar
{
  attr1 = "val1"
  nested {
    attr2 = "val2"
  }
}
```

Nice job on `hcledit` and thanks for sharing this tool with the community.

**Comment by minamijoyo** [comment]
Hi @nitrocode, thank you for reporting!
 
The type of last 2 is block rather than attribute. So I expect to get it with `hcledit block get`.
I tested and confirmed that the top level block seems to be ok, but the nested doesn't.

```
$ cat test.tf | hcledit block get resource.foo.bar.nested
```

```
$ cat test.tf | hcledit block get resource.foo.bar
resource "foo" "bar" {
  attr1 = "val1"
  nested {
    attr2 = "val2"
  }
}
```

I agree it's natural to expect returning the nested block as the same as the nested attribute. We should support it.

Strictly speaking, the `hcledit block get` returns not only block body `{ ... }`, but also block header `resource "foo" "bar"`. Do you want to get the block body without the header? if so, we need to support `hcledit body get`.

**Comment by nitrocode** [comment]
Yes I agree with you. I didn't realize there was a block get command.

As you already mentioned, ybese changes would be nice

* Support `body get` to retrieve body without header
* Support `block get` for blocks

**Comment by minamijoyo** [comment]
@nitrocode The `hcledit block get` command now returns not only the top-level block, but also the nested block. See #22

**Comment by minamijoyo** [comment]
@nitrocode I added `hcledit body get` command in #23.

The expected behavior you described above contains the outer brackets `{}`, however, according to the HCL spec, the outer brackets don't belong to the body.
https://github.com/hashicorp/hcl/blob/v2.9.1/hclsyntax/spec.md#structural-elements

So, I intentionally didn't include them in the outputs.
