### ISSUE TITLE
Don't output comma at the end of lists

### ISSUE THREAD

**Issue by ChristophShyper** [minamijoyo/hcledit#80]
Hi. Great piece of work, I really appreciate it.

But technically correct HCL is causing some minor issues, e.g.
```hcl
  list = [
    "item1",
    "item2",
  ]
```
Is outputted exactly like that with `hcledit attribute get`:
```hcl
[
    "item1",
    "item2",
  ]
```

When I later parse it with `jq -r '.[]` it throws error `parse error: Expected another array element at line 4, column 3`.

Output from `hcledit attribute get` shouldn't show the comma after the last element of a list.

**Comment by minamijoyo** [comment]
Technically speaking, the comma at the end of a list is a valid expression in HCL's native syntax. Your proposal doesn’t make sense because the output is an expression in HCL's native syntax and not JSON. Unsurprisingly, it cannot be parsed as JSON.

To convert HCL to JSON, use another tool, such as hcl2json: https://github.com/tmccombs/hcl2json

```
$ cat tmp/list.hcl
list = [
  "item1",
  "item2",
]

$ cat tmp/list.hcl | hcl2json
{
    "list": [
        "item1",
        "item2"
    ]
}

$ cat tmp/list.hcl | hcl2json | jq -r ".list[]"
item1
item2
```
