### ISSUE TITLE
`dynamic` block support

### ISSUE THREAD

**Issue by beatcracker** [minamijoyo/hcledit#90]
### Version

```shell
hcledit version
0.2.10
```

### Example

- `repro.tf`
```hcl
resource "foo" "bar" {
  attr = "value"

  dynamic "baz" {
    for_each = var.qux != "" ? [1] : []
    content {
      dyn_attr = "value"
    }
  }
}
```

Check if `dynamic` block can be addressed:

```shell
hcledit -f ./repro.tf block list
resource.foo.bar

hcledit -f ./repro.tf attribute get resource.foo.bar.attr
"value"

hcledit -f ./repro.tf attribute get resource.foo.bar.dynamic
hcledit -f ./repro.tf attribute get resource.foo.bar.dynamic.baz
```

**Comment by minamijoyo** [comment]
Hi @beatcracker, The attribute sub command is only for attributes. You can use block or body instead. 

```
$ hcledit -f ./repro.tf block get resource.foo.bar.dynamic.baz
dynamic "baz" {
  for_each = var.qux != "" ? [1] : []
  content {
    dyn_attr = "value"
  }
}
```

```
$ hcledit -f ./repro.tf body get resource.foo.bar.dynamic.baz
for_each = var.qux != "" ? [1] : []
content {
  dyn_attr = "value"
}
```

**Comment by beatcracker** [comment]
Oh, wow! For some reason I was expecting `block` or `body` to work only with top-level entries. Had a look at the docs and it's right there 🤦🏻.

Bonus question, why there is no `set` command for `block` or `body`? Could be very useful.

**Comment by minamijoyo** [comment]
In HCL, a block is a container that has labels and a body. A body is also a container that has attributes and blocks. A block can be nested at any level. Also, the labels of the blocks can be duplicated. Since a block is not a simple primitive like an attribute, it can be a complex data structure; I have not yet come up with a good interface for setting them from the CLI.

For now, a new block can be added with the `block append` command, and new attributes can be added on the block with the `attribute append` command. If your use case is too complex to assemble blocks with the CLI, consider using Go libraries such as the low-level [hashicorp/hcl](https://github.com/hashicorp/hcl), `minamijoyo/hcledit` as a Go library, or a more high-level Terraform specific one [minamijoyo/tfedit](https://github.com/minamijoyo/tfedit) as a Go library.
